### ISSUE TITLE
Unable to find genome in >700...

### ISSUE THREAD

**Issue by GrantHov** [rhysf/Synima#23] opened 2021-07-22 17:56 UTC
Hi, 

In your example, when I run 

perl ../util/Blast_grid_all_vs_all.pl -r ./Repo_spec.txt -t CDS

I get the error

fasta_id_to_seq_hash: saving sequences from ./Repo_spec.txt.all.CDS...
Splitting seq dictionary for blasting...
Cryp_gatt_CA1280_V1 = ./Cryp_gatt_CA1280_V1/Cryp_gatt_CA1280_V1_FINAL_CALLGENES_1.annotation.cds.synima-parsed.CDS...
Unable to find genome in >7000010363293464 7000010363293459 I312_00500 name="FK506-binding protein 1" at index 3

Any thoughts on how to deal with it?

**Comment by rhysf** [comment] 2021-07-23 12:04
Hi @GrantHov 

Thanks for bringing this to my attention. It's evidently been a while since CDS have been used (rather than the default PEP). I found that the ids in the CDS fasta were not being formatted in the same way as the PEP fasta, creating the problem you encountered.

I have updated the code to work with the example CDS data, and it should now be more applicable across the range of fasta id's it may encounter.

You'll have to re-clone Synima, and start afresh from Create_full_repo_sequence_databases.pl.

Hope that helps and please let me know if you run into any further difficulties,

Best,
Rhys

**Comment by GrantHov** [comment] 2021-07-27 09:47
Hi Rhys,

Thanks for fixing the issue, the the pipeline works as expected.
However I have a more specific issue now with is related to the data I analyze -  I work with lncRNAs across distantly related yeast species, and apparently there are almost no blast hits among them. So when I reach the final step of plotting, the software output only 4 genomes instead of 5 that I work with (this last one is the most distant species). Is it possible to tweak the software to plot all genome even if there are not orthologs (let me know if I should open a separate issue for this)?

**Comment by rhysf** [comment] 2021-07-27 10:07
Hi @GrantHov 

I'm glad that fix solved the issue. 

Your new issue of no genome being plotted when there is no syntenic genes could probably be solved by adding a pseudo-entry into your aligncoords file (i.e. just make one up between your missing genome and one that is present). 

Alternatively, you could use the Synima pipeline for your protein encoding genes and lncRNAs to generate a synteny plot across the genomes as intended, and then you can use the gene id's in the config file or on the command line (e.g. -k, -l, -o) to show the genomic locations of your lncRNA's that are synteny. Currently those 'gene list' parameters do not show genes that are not in synteny - so if you want to show the locations for all of them, you would need to edit the R script Synima produces and run that on the command line or in R studio for example.

I hope that helps. Given your initial issue has now been solved, i'll close this issue. 
Best,
Rhys


. However, i'm not sure that will be very informative 

this isn't going to be very informative to do so. Synima is designed to plot synteny, so if there is none, it

why you would want to plot the genome without any synteny - given


is less easy to solve, as the orthology pipeline isn't intended to work with zero hits - so, i'm not sure what y

**Closed by rhysf** 2021-07-27 10:07 UTC
