### ISSUE TITLE
DAGchainer_from_gene_clusters.pl produces empty aligncoords file

### ISSUE THREAD

**Issue by zcalamari** [rhysf/Synima#22] opened 2021-01-24 05:29 UTC
Hello, I am trying to use Synima on two mammalian genomes and the dagchainer step appears to be having an issue, but produces no error message. Although there are over 64,000 lines in the hit_pairs file, the hit_pairs.aligncoords file is empty. The last line that prints to stderr is "save_gene_struct_from_gff: parsing ./Myodes/Myodes.annotation.gff3.synima-parsed.GFF3 for Myodes" and the stdout only says "Done. Final dagchainer output provided as: ./Repo_spec.txt.dagchainer.aligncoords."

I am not sure if there is a setting I have missed or if there are parameters I can optimize to address this. Any help would be appreciated!

**Comment by rhysf** [comment] 2021-01-24 13:39
Hi @zcalamari 

To try and solve the issue, i'll need you to include the full command you used and all standard out and standard error from running that command.
Thanks,
Rhys

**Comment by zcalamari** [comment] 2021-01-24 15:45
Command: 
perl ../util/DAGchainer_from_gene_clusters.pl -r ./Repo_spec.txt -c GENE_CLUSTERS_SUMMARIES.RBH/GENE_CLUSTERS_SUMMARIES.clusters

Standard error: 
save_genomes_of_interest...
save_genomes_of_interest: found 2 genomes
save_gene_ids_from_ortholog_file: GENE_CLUSTERS_SUMMARIES.RBH/GENE_CLUSTERS_SUMMARIES.clusters...
save_gene_ids_from_ortholog_file: found 2 genomes
process_orthocluster_results_into_hit_pairs: found 2 genomes
save_gene_struct_from_gff: parsing ./Repo_spec.txt.all.GFF3 for all
Splitting GFF by genomes...
Mus = ./Mus/Mus.annotation.gff3.synima-parsed.GFF3...
Myodes = ./Myodes/Myodes.annotation.gff3.synima-parsed.GFF3...
Writing DAGChainer config file dagchainer_rundir/dagchainer.cmds for 2 genomes...
Running DAGchainer commands...
Running /mendel-nas1/zcalamari/Synteny/Synima/util/support_scripts/run_DAG_chainer.pl -c dagchainer_rundir/Mus_vs_Myodes.dagchainer.conf -z n -v n
Saving dagchainer config dagchainer_rundir/Mus_vs_Myodes.dagchainer.conf...
save_gene_struct_from_gff: parsing ./Mus/Mus.annotation.gff3.synima-parsed.GFF3 for Mus
save_gene_struct_from_gff: parsing ./Myodes/Myodes.annotation.gff3.synima-parsed.GFF3 for Myodes

Standard out:
Done. Final dagchainer output provided as: ./Repo_spec.txt.dagchainer.aligncoords

**Comment by zcalamari** [comment] 2021-01-24 15:46
In case it is also helpful, the commands I ran for the earlier steps were:
perl ../util/Create_full_repo_sequence_databases.pl -r ./Repo_spec.txt
perl ../util/Blast_grid_all_vs_all.pl -r ./Repo_spec.txt -o ./blast.PEP.cmds
perl ../util/Blast_all_vs_all_repo_to_RBH.pl -r ./Repo_spec.txt
perl ../util/Orthologs_to_summary.pl -o ./RBH_outdir/PEP.RBH.OrthoClusters -t RBH

**Comment by rhysf** [comment] 2021-01-25 10:36
Can you confirm that GENE_CLUSTERS_SUMMARIES.RBH/GENE_CLUSTERS_SUMMARIES.clusters has entries in it, how many lines the file has, and perhaps paste the head of the file here?

Can you also check the size of your .m8 blast files in the folders made within your genome directories (the folder should be called RBH_blast_PEP) - and make sure that a reasonable number of blast hits were identified. If not, then you will need to delete those files and re-run from that step.

Another suggestion, is depending on the distance between your two species, it is possible that there are no chains of 4 or more orthologs. That sounds unlikely, but it could be worth reducing -i and seeing if that changes anything. Also, could you re-run this step with -v y (Verbose) as that may give a little more information about what might not be working.

Best,
Rhys

**Comment by zcalamari** [comment] 2021-01-26 14:22
Hi Rhys,

GENE_CLUSTER_SUMMARIES.clusters has 19592 clusters in it. The head looks like this:
1	Mus	Ortho	ENSMUSP00000031255.8	ENSMUSP00000031255.8	ENSMUSP00000031255.8	hypothetical protein
1	Mus	Ortho	ENSMUSP00000108508.1	ENSMUSP00000108508.1	ENSMUSP00000108508.1	hypothetical protein
1	Mus	Ortho	ENSMUSP00000090667.3	ENSMUSP00000090667.3	ENSMUSP00000090667.3	hypothetical protein

2	Mus	InPara	ENSMUSP00000131532.1	ENSMUSP00000131532.1	ENSMUSP00000131532.1	hypothetical protein
2	Mus	InPara	ENSMUSP00000065010.6	ENSMUSP00000065010.6	ENSMUSP00000065010.6	hypothetical protein

3	Mus	Ortho	ENSMUSP00000155973.1	ENSMUSP00000155973.1	ENSMUSP00000155973.1	hypothetical protein
3	Mus	Ortho	ENSMUSP00000104230.2	ENSMUSP00000104230.2	ENSMUSP00000104230.2	hypothetical protein

The Mus vs Mus .m8 file has 9,246,365 hits, the Mus vs Myodes .m8 file has 226,493. The Myodes vs Mus .m8 has 115,537 hits, and the Myodes vs Myodes file has 2,306,373 hits. The annotation for the Myodes genome has 27,824 peptides, so that would seem to be a reasonable number of hits to me, but I can adjust the e-value if this search should return more results than that.

This is the verbose standard error (I also ran it with -i 3 and it still produced no results):
save_genomes_of_interest...
save_genomes_of_interest: found 2 genomes
save_gene_ids_from_ortholog_file: GENE_CLUSTERS_SUMMARIES.RBH/GENE_CLUSTERS_SUMMARIES.clusters...
save_gene_ids_from_ortholog_file: found 2 genomes
process_orthocluster_results_into_hit_pairs: found 2 genomes
save_gene_struct_from_gff: parsing ./Repo_spec.txt.all.GFF3 for all
Splitting GFF by genomes...
Myodes = ./Myodes/Myodes.annotation.gff3.synima-parsed.GFF3...
Mus = ./Mus/Mus.annotation.gff3.synima-parsed.GFF3...
Writing DAGChainer config file dagchainer_rundir/dagchainer.cmds for 2 genomes...
Running DAGchainer commands...
Running /mendel-nas1/zcalamari/Synteny/Synima/util/support_scripts/run_DAG_chainer.pl -c dagchainer_rundir/Mus_vs_Myodes.dagchainer.conf -z n -v y
Saving dagchainer config dagchainer_rundir/Mus_vs_Myodes.dagchainer.conf...
Parsing matches file: dagchainer_rundir/Mus_vs_Myodes.hit_pairs...
Saving gene features...
save_gene_struct_from_gff: parsing ./Myodes/Myodes.annotation.gff3.synima-parsed.GFF3 for Myodes
save_gene_struct_from_gff: parsing ./Mus/Mus.annotation.gff3.synima-parsed.GFF3 for Mus
Linking feature IDs to genes...
Ordering genes on scaffolds...
Grouping matches by organism/molecule pairs...
Applying noise filter...
-running DAGchainer -> dagchainer_rundir/Mus_vs_Myodes.hit_pairs.aligncoords

**Comment by rhysf** [comment] 2021-01-26 15:54
Hi @zcalamari 

OK, in that case, I'm not sure what the issue is. It looks like you have got the orthologs part of the pipeline working, but not the synteny part. 

I think i'll need to run the command myself and take a deeper look. If you are willing to give me access to your input files (Repo_spec.txt, Repo_spec.txt.all.GFF3, GENE_CLUSTER_SUMMARIES.clusters) - then I can try. Those files are probably rather large, so perhaps you can put them on Dropbox, google drive or something like that, and i'll download them from there and let you know. My email is rfarrer at broadinstitute dot org

Thanks,
Rhys

**Comment by rhysf** [comment] 2021-01-27 23:41
We think the issue stems from IDs in the input files not properly matching up in the first step (Create_full_repo_sequence_databases.pl), so i'm closing this issue now.

**Closed by rhysf** 2021-01-27 23:41 UTC
